name: Release
on:
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Version from Package File
        id: get-version 
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Get Version of Release Branch
        run: echo "BRANCH_VERSION=$(echo $GITHUB_HEAD_REF | sed 's/releases\///g')"
        