name: Release
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check Version from Package File
        id: get-version 
        run: |
          PACKAGE_VERSION=node -p -e '`${require("./package.json").version}`'
          if git show-ref --tags --verify --quiet "refs/tags/${{ env.PACKAGE_VERSION }}"; then
            echo "Tag $PACKAGE_VERSION exists"
            echo "MY_MSG=Error: Package Version $PACKAGE_VERSION is already used. Associated tag already exists." >> $GITHUB_ENV 
          else
            echo "Tag PACKAGE_VERSION does not exist"
          fi

      - name: Check Version of Release Branch
        if:  startsWith(github.head_ref, 'releases/')
        run: |
          echo -n "BRANCH_VERSION=$(echo $GITHUB_HEAD_REF | sed 's/releases\///g')" >> $GITHUB_ENV
          if git show-ref --tags --verify --quiet "refs/tags/${{ env.BRANCH_VERSION }}"; then
            echo "Tag ${{ env.BRANCH_VERSION }} exists"
            echo "MY_MSG=${{ env.MY_MSG }} Error: Package Version ${{ env.PACKAGE_VERSION }} is not correct. Tag already exists." >> $GITHUB_ENV 
          else
            echo "Tag ${{ env.BRANCH_VERSION }} does not exist"
          fi
      
      - name: Fail PR if versions not matching
        if: ${{ env.PACKAGE_VERSION != env.BRANCH_VERSION }}
        run: echo "versions not matching"

      - name: Check for Tag
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${{ env.PACKAGE_VERSION }}"; then
            echo "Tag ${{ env.PACKAGE_VERSION }} exists"
          else
            echo "Tag ${{ env.PACKAGE_VERSION }} does not exist"
          fi

      - uses: actions/github-script@v6
        with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '${{ env.MY_MSG }}'
              })
