name: Release
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version from Package File
        id: get-version 
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Get Version of Release Branch
        run: echo -n "BRANCH_VERSION=$(echo $GITHUB_HEAD_REF | sed 's/releases\///g')" >> $GITHUB_ENV
      
      - name: Fail PR if versions not matching
        if: ${{ env.PACKAGE_VERSION != env.BRANCH_VERSION }}
        run: echo "versions not matching"

      - name: Check for Tag
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${{ env.BRANCH_VERSION }}"; then
            echo "Tag ${{ env.BRANCH_VERSION }} exists"
          else
            echo "Tag ${{ env.BRANCH_VERSION }} does not exist"
          fi