name: Tag & Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Get Version from Package File
      id: get-version 
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

    - name: Create Tag
      id: create-tag
      uses: anothrNick/github-tag-action@1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.PACKAGE_VERSION }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ steps.create-tag.outputs.new_tag }}
        token: ${{ secrets.PAT_RELEASE }}
